### ISSUE TITLE
Create context diagram with epics

### ISSUE THREAD

**Issue by furrkai** [gcivil-nyu-org/S2022-Team-1-repo#22]
After epics are finalized, the context diagram is needed in the project wiki page. See details here. https://www.romanpichler.com/blog/user-story-modelling/ Next, the team need to create Zenhub cards for these epics.

**Comment by weineng-hsu** [comment]
After the discussion, there are five epics in total. User registration and login, search and browse through posts, manage posts, connect with the post owner, and modify profile page. The descriptions of each epic are listed on the project wiki page.  See here for more detail. https://github.com/gcivil-nyu-org/S2022-Team-1-repo/wiki/High-Level-Analysis

**Comment by weineng-hsu** [comment]
The epic Zenhub cards are created.
