### ISSUE TITLE
Identify epics and write description

### ISSUE THREAD

**Issue by furrkai** [gcivil-nyu-org/S2022-Team-1-repo#23]
Identify the epics of our project, NYU marketplace, and write down the descriptions of those epics in our project wiki page.

**Comment by weineng-hsu** [comment]
After the discussion, there are five epics in total. User registration and login, search and browse through posts, manage posts, connect with the post owner, and modify profile page. The descriptions of each epic are listed on the project wiki page. See here for more detail. https://github.com/gcivil-nyu-org/S2022-Team-1-repo/wiki/High-Level-Analysis
