### ISSUE TITLE
As a post owner, I want to be able to view the post I created so I can verify my post details.

### ISSUE THREAD

**Issue by Shravanirakshe** [gcivil-nyu-org/S2022-Team-1-repo#56]

**Comment by weineng-hsu** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/S2022-workspace-620189b09c1e3d001abf18bf/issues/gcivil-nyu-org/S2022-Team-1-repo/56?planning-poker) with ZenHub @abirbhav @nevermoreno1 @furrkai @Shravanirakshe
